### ISSUE TITLE
rvctool: ImportError: cannot import name 'randn' from 'scipy'

### ISSUE THREAD

**Issue by odadaj** [petercorke/RVC3-python#16] opened 2024-03-01 03:30 UTC
Trying to run rvctool after installation gives an error as shown in the attached image.
![error](https://github.com/petercorke/RVC3-python/assets/383275/11cf6c5a-add0-44da-a31b-08438f43cf41)

**Comment by odadaj** [comment] 2024-03-04 11:03
I tested python version 3.10, 3.9, 3.8 and 3.7. 
Only 3.8 worked without any issues 3.9 and 3.10 gave the error above.

**Comment by hualex** [comment] 2024-03-06 01:48
![d3ec6dfaa244f411070df30227ca4dd](https://github.com/petercorke/RVC3-python/assets/2457190/0d9cca12-1474-4587-bf45-62f027d2cec6)

same issue here both on windows 11 and ubuntu 20.04

**Comment by leandawnleandawn** [comment] 2024-03-14 12:31
Same issue here 
![image](https://github.com/petercorke/RVC3-python/assets/83767299/abc02998-4753-4631-be6e-4eead4ef911d)

The following distribution that I use is Ubuntu Mate 22.04.4 LTS version

**Comment by tejashah88** [comment] 2024-04-05 03:02
For anyone dropping by here, this issue is documented in the robotics-toolbox-python repo here: https://github.com/petercorke/robotics-toolbox-python/issues/412. The crux of the problem is that SciPy removed the 'randn' import in v1.12.0, which is incompatible with the current version of the toolbox.

There's a hotfix that can be used for the time being, which installs a version of scipy less than v1.12.0: `pip install "scipy<1.12.0"`

There is also a propsed PR (https://github.com/petercorke/robotics-toolbox-python/pull/413) which fixes the problem by removing the import since it's not even being used, but given that it's 3 months old and hasn't had any attention from the author, I'd recommend sticking to the hotfix for now.

**Comment by petercorke** [comment] 2024-05-22 01:37
Sorry about the long delay in sorting this.  This was fixed in 1.1.1 posted earlier this month.

**Closed** 2024-05-22 02:23 UTC
Labels: bug

**Comment by tejashah88** [comment] 2024-05-23 07:33
@petercorke Thanks for the response! Also might be helpful to update the Anaconda version to 1.1.1 for anyone else using it

**Comment by slyandsmart** [comment] 2024-12-22 16:19
@petercorke  thanks for your effort, i think 
still there is no wheel for linux now on the 1.1.1. version, so it is not solved for linux i gues..

it would be sure helpfull for all linux/ros2 users
